### ISSUE TITLE
reloadMetadata not in scope

### ISSUE THREAD

**Issue by mrvdb** [d12frosted/d12frosted.github.io#1]
The solution you chose for the metadata for orgmode files in a hakyll setup was exactly what I needed, but there seems to be a part missing. 

```
src/Compiler/Pandoc.hs:16:11: Not in scope: ‘reloadMetadata’
```

Is this the 'patched hakyll' you mention on http://d12frosted.github.io/posts/Back-to-pandoc.html ?

**Comment by d12frosted** [comment]
@mrvdb you have to use `features/reloadMetadata` branch from [my fork](https://github.com/d12frosted/hakyll/tree/features/reloadMetadata). It's not up to date with upstream currently, but I think it's easy to do. 

And yes, this is what I've mentioned in that post :smile_cat:

**Comment by mrvdb** [comment]
Thanks, I'll give that a shot.

**Comment by d12frosted** [comment]
Let me know if something goes wrong

**Comment by mrvdb** [comment]
I got it working (just tested with /title/ now), but it works like I expected. As I compiled against latest hakyll, the only thing I needed to adjust for was the changed interface for pandoc `Link` :
``` diff
--- src/Compiler/Org.hs 2016-04-05 17:41:57.387792761 +0200
+++ ../_tools/d12frosted.github.io/src/Compiler/Org.hs  2016-04-05 14:15:09.225407462 +0200
@@ -71 +71 @@
-  = Plain [Link nullAttr headerText ("#" ++ headerId nums, "")] :
+  = Plain [Link headerText ("#" ++ headerId nums, "")] :
@@ -151 +151 @@
-modLinks (Link nullAttr content (url', title)) = Link nullAttr content (url, title)
+modLinks (Link content (url', title)) = Link content (url, title)
```

Thanks again, this helped a lot!

**Comment by d12frosted** [comment]
You're welcome. If you wish, you could PR this here :)

**Comment by mrvdb** [comment]
Am I correct that tags do not work (yet) or am I missing something? 

That is, they work fine as plain string metadata, but handling with `buildTags` for example does not seem to work.

**Comment by d12frosted** [comment]
Yes, I believe that tags are not yet fully supported, though it's not hard to add them. How do you place tags in your original post that you compile? 

```
#+TAGS: tag1 tag2
```

**Comment by d12frosted** [comment]
Yes, you should just add special transformer for tags, like I've [done][2] for [date][1].

  [1]: https://github.com/d12frosted/d12frosted.github.io/blob/source/src/Compiler/Org.hs#L29
  [2]: https://github.com/d12frosted/d12frosted.github.io/blob/source/src/Compiler/Org.hs#L23

I am updating my hakyll fork and will update this repo pretty soon (and will merge your PR). If it's not urgent for you - I can implement. Otherwise - you are welcome to send PR :)

**Comment by d12frosted** [comment]
Ok, just pushed [commit][1] that fixes initial issue. It will automatically use my fork when you use `stack` to build this blog. Thanks for report :) 

  [1]: https://github.com/d12frosted/d12frosted.github.io/commit/89024865d6fbabffe761d7a4572761e146afe20f

**Comment by mrvdb** [comment]
Yes, entering tags like you wrote. 

I'm redoing my site in Hakyll to learn Haskell, so yeah, i'd like to try writing a transformer, but I don't understand the need for them. What makes `date` and `tags` different from other meta fields?

Reading the code for the date transformer; is this just to convert org-mode date representations like `<yyyy-mm-dd>` to an acceptable format?

**Comment by d12frosted** [comment]
> What makes date and tags different from other meta fields?

It's because I use dates in org format. Tags? Well, we use space to separate tags, while Hakyll (and Jekyll) use comma as separator. So ideally changing space to comma should be enough. :smile:

**Comment by mrvdb** [comment]
Ah, simpler than I though then.

However, I think there is another issue then, because even with comma separated tags header field it doesn't work unless I'm doing something wrong

**Comment by d12frosted** [comment]
See my [last commit][1], where I've added support of tags. 

In order to add these tags on post page modify `templates/post.html` like this.

```
$body$

<div id="info">
  <p>Tagged as: $prettytags$.</p>
  <p>
    Posted on $date$
    $if(author)$
      by $author$
    $endif$
  </p>
  <p>
    Source: <a href="https://github.com/d12frosted/d12frosted.github.io/blob/source/$path$">$title$</a>
  </p>
</div>
```

What you have to keep in mind - you can't get tags before `pandocMetadataCompilerWith` is called (I call it using `orgCompiler`). Otherwise your tags will not be in cached metadata. It might be tricky :) 

  [1]: https://github.com/d12frosted/d12frosted.github.io/commit/9f21f845088e3402faeaffa9a1ef3471d61b75d8

**Comment by mrvdb** [comment]
Thanks man, you're fast!

That last commit was the missing link indeed.

I've been using buildTags (which builds a comma separated list with links automatically) instead of getTags. I need to play with this a bit to understand what is happening and gain some control over the format.

**Comment by d12frosted** [comment]
Glad to hear :)

Well yes, using `pandocMetadataCompilerWith` is a bit tricky thing, because now you have to think about **order** of execution. You have to call compilers that operate on metadata after `pandocMetadataCompilerWith`. There is one silly workaround - call `pandocMetadataCompilerWith` before anything else - even before real posts compiler :) But I never tried it :smile_cat:

**Comment by mrvdb** [comment]
@d12frosted FYI: here's the solution I've chosen for now (changed my mind on buildTags again) -> https://github.com/mrvdb/mrblog/blob/hakyll-migration/src/Main.hs#L127
